# Generated by Django 5.2.1 on 2025-05-21 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cargo', models.CharField(max_length=100)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_prestamo', models.DateField()),
                ('cantidad_solicitada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_aprobada', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('plazo', models.PositiveIntegerField(help_text='Plazo en meses')),
                ('interes', models.DecimalField(decimal_places=2, help_text='Interés porcentual', max_digits=5)),
                ('fecha_aprobacion', models.DateField(blank=True, null=True)),
                ('cuota', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('estado_prestamo', models.BooleanField(default=True)),
                ('nota_prestamo', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=15, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_socios/')),
                ('fecha_ingreso', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='PagoPrestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cuota_pago', models.PositiveIntegerField()),
                ('saldo_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('capital_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('interes_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('plazo_pago', models.PositiveIntegerField(help_text='Plazo restante en meses')),
                ('valor_cuota_pago', models.DecimalField(decimal_places=2, max_digits=12)),
                ('estado', models.BooleanField(default=True)),
                ('fecha_pago', models.DateField()),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='app_cajaAhorros.prestamo')),
            ],
        ),
        migrations.AddField(
            model_name='prestamo',
            name='garante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='garante_prestamos', to='app_cajaAhorros.socio'),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='app_cajaAhorros.socio'),
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle_movimiento', models.TextField()),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fecha_movimiento', models.DateField()),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='app_cajaAhorros.socio')),
            ],
        ),
        migrations.CreateModel(
            name='Directiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_directiva', models.BooleanField(default=True)),
                ('fecha_eleccion', models.DateField()),
                ('fecha_salida', models.DateField(blank=True, null=True)),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directivas', to='app_cajaAhorros.cargo')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='directivas', to='app_cajaAhorros.socio')),
            ],
        ),
    ]
