# Generated by Django 5.2.1 on 2025-05-29 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='detalle_movimiento',
            field=models.CharField(),
        ),
    ]
