# Generated by Django 5.2.1 on 2025-05-30 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0002_alter_movimiento_detalle_movimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
