# Generated by Django 5.2.1 on 2025-05-31 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0003_socio_activo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20, unique=True)),
                ('nombre_empresa', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('ciudad', models.CharField(max_length=100)),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('plazo_maximo', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='prestamo',
            old_name='nota_prestamo',
            new_name='nota',
        ),
        migrations.RemoveField(
            model_name='prestamo',
            name='estado_prestamo',
        ),
        migrations.AddField(
            model_name='pagoprestamo',
            name='fecha_a_pagar',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado')], default='Solicitado', max_length=20),
        ),
        migrations.AddField(
            model_name='socio',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='socio',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cuota',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_prestamo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='interes',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
