# Generated by Django 5.2.1 on 2025-05-31 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0004_configuracion_rename_nota_prestamo_prestamo_nota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado')], default='Solicitado', max_length=20),
        ),
    ]
