# Generated by Django 5.2.1 on 2025-06-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0005_alter_prestamo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagoprestamo',
            name='fecha_pago',
            field=models.DateField(blank=True, null=True),
        ),
    ]
