# Generated by Django 5.2.1 on 2025-06-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0006_alter_pagoprestamo_fecha_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='detalle_movimiento',
            field=models.CharField(max_length=255),
        ),
    ]
