# Generated by Django 5.2.1 on 2025-06-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0007_alter_movimiento_detalle_movimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='interes',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
