# Generated by Django 5.2.1 on 2025-06-10 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0008_alter_prestamo_interes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GastosAdministrativos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('entrada', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('salida', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('saldo', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.AddField(
            model_name='configuracion',
            name='aporte_inicial',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='gastos_adm',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
