# Generated by Django 5.2.1 on 2025-06-10 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0009_gastosadministrativos_configuracion_aporte_inicial_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='estado',
            field=models.CharField(choices=[('Solicitado', 'Solicitado'), ('Pendiente', 'Pendiente'), ('Aprobado', 'Aprobado'), ('Rechazado', 'Rechazado'), ('Terminado', 'Terminado')], default='Solicitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='garante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='garante_prestamos', to='app_cajaAhorros.socio'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='prestamos', to='app_cajaAhorros.socio'),
        ),
    ]
