# Generated by Django 5.2 on 2025-06-12 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0010_alter_prestamo_estado_alter_prestamo_garante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagoprestamo',
            name='comprobante_pago',
            field=models.ImageField(blank=True, null=True, upload_to='comprobante_pago/'),
        ),
        migrations.AddField(
            model_name='pagoprestamo',
            name='detalle_pago',
            field=models.TextField(blank=True, null=True),
        ),
    ]
