# Generated by Django 5.2 on 2025-06-13 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0011_pagoprestamo_comprobante_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracion',
            name='tasa_prestamo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
