# Generated by Django 5.2.1 on 2025-06-14 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_cajaAhorros', '0012_configuracion_tasa_prestamo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rol',
        ),
    ]
